### PR TITLE
lwt.2.6.0 -> lwt.3.0.0

### PR DESCRIPTION
**Pull request by pirbo**
Also add the conflict with conf-flambda-windows

### CODE REVIEW

**Comment by whitequark** [comment]
This is a new major version of lwt, maybe add them both concurrently?

**Comment by pirbo** [comment]
It sounds reasonable indeed.

**Comment by pirbo** [comment]
Sorry, is there an other reason for not merging? (Lack of time to review is a good one.)

**Comment by whitequark** [comment]
@pirbo No reason at all, GH did not send me the mail about new pushed commits for some reason and I haven't realized from your other comment that you've already updated the PR.

**Comment by whitequark** [comment]
Can you please rebase the PR so that there are separate commits adding lwt-react-windows.1.0.1 and lwt.3.0.0? And then another one to make lwt.2.6.0 conflict with flambda.

**Comment by pirbo** [comment]
Done.

**Pull request merged**
