### PR TITLE
Lots of new packages

### PR DESCRIPTION
**Pull request by hcarty**
These are all relatively simple/straightforward ports.

This includes a few fixes:
- #12 in 783bfca
- rresult build instructions fixed in 1ecda16

I have more packages that I'm working on cleaning up to make them suitable for inclusion, mostly centered around getting the dependencies for cohttp ready.  Lots of ppx required in that toolchain.  Those will be in another PR since they're less straightforward.

### CODE REVIEW

**Comment by whitequark** [comment]
I have a few comments:

  * Please do not use base-unix as this is irrelevant for cross-toolchain. unix, threads, etc are always available by definition in opam-cross-{windows,android} (I think iOS has a slightly different situation but it is also not subject to variation).
  * Please do not depend on ocamlfind, instead depend on ocaml-windows explicitly. This avoids issues when a package is updated and dependencies are added/removed, since e.g. if fmt-windows somehow drops the dep on result-windows, it will not depend on ocaml-windows transitively at all. The ocamlfind dependency is implied in ocaml-windows as this is how the cross-toolchains work.
  * Please do not depend on build system conf-* packages, like you do with conf-which in bos-windows. This does not do what you want.
  * Please follow the convention for the git log lines that's already used in the repo, I have some automation ideas for which it will be useful.

Otherwise I have no comments, and will gladly merge the PR.

**Comment by hcarty** [comment]
Thank you for all of the feedback - I'll update the PR to address each, hopefully within the next few days.

**Comment by hcarty** [comment]
@whitequark I have made the changes you requested:
- No more `base-unix`, `ocamlfind` or `conf-*`
- Commit messages should match your conventions now

Please let me know if there are other changes you'd like to see before merging.

**Comment by whitequark** [comment]
On 2016-12-07 18:17, Hezekiah M. Carty wrote:
> @whitequark [1] I have made the changes you requested:
> 
>  	* No more base-unix, ocamlfind or conf-*
>  	* Commit messages should match your conventions now
> 
> Please let me know if there are other changes you'd like to see before
> merging.

Yes. You are using the %{ocaml-native}% variable (and native-dynlink 
also)
which is wrong for the same reason as base-unix.

Also, do you think you can patch the setup.ml in zmq? This is 
counterintuitively
less fragile than patching _oasis file as it makes it easier to upgrade 
the package.

base64-windows still has a base-bytes dependency. (I should extend opam 
lint or
something...)

Otherwise it looks like everything is fine.

-- 
whitequark

**Comment by hcarty** [comment]
- `base`/`conf`/`%{*native*}%` should be gone now
- zmq has a patch for `setup.ml` and `myocamlbuild.ml` made by manually editing those files

**Comment by whitequark** [comment]
I'm happy enough with your changes that I gave you commit bit.

**Comment by hcarty** [comment]
Thanks, and thank you for taking the time for a detailed review.

**Pull request merged**
